project:
  type: website
  output-dir: docs

website:
  title: "satRday MyCity"
  sidebar: false
  navbar:
    background: light # or your hex color
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - text: satRday conference
            href: about/about.qmd
          - text: Organizing committee
            href: about/organizers.qmd
          - text: Sponsors
            href: about/sponsors.qmd
          - text: Diversity statement
            href: about/diversity.qmd
      - text: Program
        menu: 
          - text: Schedule
            href: schedule.qmd
          - text: Speakers
            href: speakers.qmd
      - text: Register
        href: register.qmd
      - text: Participation
        menu: 
          - text: Call for Abstracts
            href: participation/call.qmd
          - text: Code of Conduct
            href: participation/coc.qmd
          - text: Key dates
            href: participation/dates.qmd
      - text: Contact
        href: contact.qmd
  page-footer: 
    left: "Proudly supported by R Consortium"
    center: "Copyright © 2023, satRdays Team" 
    right: 
      - icon: globe
        href: https://satrdays.org
      - icon: github
        href: https://github.com/satrdays
      - icon: twitter 
        href: https://twitter.com/satrdays
      - icon: envelope
        href: mailto:city@satrdays.org

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    include-after-body:
      - js/countdown.js
    page-layout: custom
    css: css/styles.css
    toc: false

editor: visual

